# Generated by Django 4.2.5 on 2023-12-22 10:54

from django.db import migrations, models
import django.db.models.deletion
# Generated by Django 4.2.5 on 2023-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_times', models.JSONField()),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
